name: Code Analysis

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    code_analysis:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-versions: ['8.1', '8.2', '8.3']
                actions:
                    -
                        name: 'Composer Validate'
                        run: composer validate

                    -
                        name: 'Rector'
                        run: composer rector

                    -
                        name: 'PHPStan'
                        run: composer phpstan

        name: ${{ matrix.actions.name }} - ${{ matrix.php-versions }}

        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: none

            -   uses: ramsey/composer-install@v3

            -   name: Rector Cache
                if: matrix.actions == 'Rector'
                uses: actions/cache@v4
                with:
                    path: /tmp/rector
                    key: ${{ runner.os }}-rector-${{ github.run_id }}
                    restore-keys: ${{ runner.os }}-rector-

            -   name: Make Folder Cache Rector
                if: matrix.actions == 'Rector'
                run: mkdir -p /tmp/rector

            -   run: ${{ matrix.actions.run }}
